export const FETCH_RECITERS = 'FETCH_RECITERS'
export const SEARCH_QUERY = 'SEARCH_QUERY'
export const FETCH_SURAHS = 'FETCH_SURAHS'
export const GET_RECITER = 'GET_RECITER'
export const GET_SURAH = 'GET_SURAH'
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'
export const LOAD = 'LOAD'
